id: P000690
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23570
  title: སྐྱེ་བོ་ཀུན་ལ་གདམ་པའི་རིན་ཆེན་ལུགས་ཀྱི་བསྟན་བཅོས་མི་ཟད་པའི་གཏེར།
  author: ''
  volumes:
    a4509bfe244a4b01b6e54458086a467a:
      image_group_id: I1KG23627
      title: ''
      volume_number: 1
      total_pages: 174
